{% set name = "cmomy" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cmomy-{{ version }}.tar.gz
  sha256: 50fe45a12e35fd01ff25b3bf2989ccf7d67d8a1de6712819e57ea1a810c2b833

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >=3.8,<3.12
    - docstring-inheritance
    - lazy_loader
    - module-utilities >=0.6
    - numba >=0.50
    - numpy >=1.21
    - typing-extensions
    - xarray >=0.16

test:
  imports:
    - cmomy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/usnistgov/cmomy
  summary: Central (co)moment calculation/manipulation
  description: |
    A Python package to calculate and manipulate Central (co)moments.
    The main features of `cmomy` are 1) Fast calculation of central
    moments and comoments with weights.  The speed comes from using
    Numba.  2) Support for scalar and vector inputs. 3) Numpy and
    xarray DataArray interface. 4) Resampling.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
